In [14]:
import pandas as pd
import numpy as np
# import Datasets
df = pd.read_csv('Datasets/dirty_cafe_sales.csv')

In [2]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [3]:
df.info() # info Datasets

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [7]:
df.isna().sum() # isna = isnull (menghitungjumlah kolom yang null dalam datasets)

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [10]:
df.isna().any(axis=1).sum() # cek berapa ada berapa baris yang memiliki null

np.int64(5450)

In [13]:
df.notna().sum() # cek jumlah kolom yang tidak null

Transaction ID      10000
Item                 9667
Quantity             9862
Price Per Unit       9821
Total Spent          9827
Payment Method       7421
Location             6735
Transaction Date     9841
dtype: int64

In [20]:
# Menghitung persentase missing value

missing_value = df.isna().sum()
missing_percentage = (missing_value / len(df)) * 100

frame = pd.DataFrame({"missing value":missing_value, "percentage" : missing_percentage})

frame

                  missing value  percentage
Transaction ID                0        0.00
Item                        333        3.33
Quantity                    138        1.38
Price Per Unit              179        1.79
Total Spent                 173        1.73
Payment Method             2579       25.79
Location                   3265       32.65
Transaction Date            159        1.59