In [2]:
import pandas as pd
import numpy as np
# import Datasets
df = pd.read_csv('Datasets/dirty_cafe_sales.csv')

In [2]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [3]:
df.info() # info Datasets

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [7]:
df.isna().sum() # isna = isnull (menghitungjumlah kolom yang null dalam datasets)

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [10]:
df.isna().any(axis=1).sum() # cek berapa ada berapa baris yang memiliki null

np.int64(5450)

In [13]:
df.notna().sum() # cek jumlah kolom yang tidak null

Transaction ID      10000
Item                 9667
Quantity             9862
Price Per Unit       9821
Total Spent          9827
Payment Method       7421
Location             6735
Transaction Date     9841
dtype: int64

In [21]:
# Menghitung persentase missing value

missing_value = df.isna().sum()
missing_percentage = (missing_value / len(df)) * 100 # (missing value / jumlah baris) x 100 untuk menjadi percent

frame = pd.DataFrame({"missing value":missing_value, "percentage" : missing_percentage})

frame

                  missing value  percentage
Transaction ID                0        0.00
Item                        333        3.33
Quantity                    138        1.38
Price Per Unit              179        1.79
Total Spent                 173        1.73
Payment Method             2579       25.79
Location                   3265       32.65
Transaction Date            159        1.59

In [4]:
# ambil 20 sample data sample
sample = df.sample(20)
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2769,TXN_2849719,Coffee,5,2.0,10.0,Digital Wallet,Takeaway,2023-06-23
1762,TXN_9749333,Cookie,5,1.0,5.0,Cash,In-store,2023-02-27
7258,TXN_7362776,Cookie,NaN,1.0,5.0,NaN,In-store,2023-01-26
6427,TXN_4197851,Salad,ERROR,5.0,15.0,Digital Wallet,In-store,2023-02-05
8118,TXN_4822216,Cake,1,3.0,3.0,NaN,NaN,2023-09-03
6857,TXN_7046631,ERROR,4,2.0,8.0,Digital Wallet,In-store,2023-05-18
1722,TXN_3873718,ERROR,1,5.0,5.0,Cash,In-store,2023-03-07
7578,TXN_4532475,Coffee,ERROR,2.0,2.0,Digital Wallet,NaN,2023-04-23
8471,TXN_8783484,Smoothie,1,4.0,4.0,Cash,In-store,2023-11-20
5998,TXN_4335735,Coffee,2,2.0,4.0,NaN,NaN,2023-04-07
6115,TXN_9672367,Cookie,2,1.0,2.0,NaN,In-store,2023-12-21
3369,TXN_6431703,Sandwich,1,4.0,NaN,Credit Card,Takeaway,2023-08-25
5894,TXN_8499618,Cake,2,3.0,6.0,ERROR,NaN,2023-05-23
7367,TXN_7951885,Salad,3,5.0,15.0,Credit Card,NaN,2023-12-08
5770,TXN_8776634,Juice,5,3.0,15.0,NaN,In-store,2023-06-02
5916,TXN_2721997,Cake,3,3.0,9.0,NaN,Takeaway,2023-05-20
6816,TXN_2526267,Sandwich,UNKNOWN,4.0,20.0,Cash,In-store,2023-04-06
9800,TXN_2954833,Coffee,1,2.0,2.0,NaN,NaN,2023-01-29
1953,TXN_7125945,Cake,3,3.0,9.0,Credit Card,In-store,2023-01-30
7333,TXN_9482559,Cookie,1,1.0,1.0,NaN,In-store,2023-08-04

In [31]:
# Menghapus missing value
sample.dropna() # dropna(inplace=true) jika mau data langsung terhapus ke df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1035,TXN_7880148,Cake,3,3.0,9.0,Credit Card,Takeaway,2023-12-12
3323,TXN_6177161,Tea,5,1.5,7.5,Credit Card,In-store,2023-04-01
6118,TXN_2252586,Tea,3,1.5,4.5,Cash,Takeaway,2023-09-08
2836,TXN_8167808,Cake,3,3.0,9.0,Cash,In-store,2023-02-03
3862,TXN_1921415,Cake,1,3.0,3.0,Cash,Takeaway,2023-11-03
3292,TXN_8568597,Juice,1,3.0,3.0,Digital Wallet,Takeaway,2023-04-03
3470,TXN_9123562,Juice,5,3.0,15.0,Credit Card,Takeaway,UNKNOWN
1192,TXN_6928137,Cake,3,3.0,9.0,Digital Wallet,In-store,2023-10-11
2482,TXN_6303383,Cake,4,3.0,12.0,Digital Wallet,In-store,2023-09-22

In [6]:
sample.dropna(thresh=7) # selama setiap baris ada 8 kolom yang terisi, tidak ada dihapus

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2769,TXN_2849719,Coffee,5,2.0,10.0,Digital Wallet,Takeaway,2023-06-23
1762,TXN_9749333,Cookie,5,1.0,5.0,Cash,In-store,2023-02-27
6427,TXN_4197851,Salad,ERROR,5.0,15.0,Digital Wallet,In-store,2023-02-05
6857,TXN_7046631,ERROR,4,2.0,8.0,Digital Wallet,In-store,2023-05-18
1722,TXN_3873718,ERROR,1,5.0,5.0,Cash,In-store,2023-03-07
7578,TXN_4532475,Coffee,ERROR,2.0,2.0,Digital Wallet,NaN,2023-04-23
8471,TXN_8783484,Smoothie,1,4.0,4.0,Cash,In-store,2023-11-20
6115,TXN_9672367,Cookie,2,1.0,2.0,NaN,In-store,2023-12-21
3369,TXN_6431703,Sandwich,1,4.0,NaN,Credit Card,Takeaway,2023-08-25
5894,TXN_8499618,Cake,2,3.0,6.0,ERROR,NaN,2023-05-23
7367,TXN_7951885,Salad,3,5.0,15.0,Credit Card,NaN,2023-12-08
5770,TXN_8776634,Juice,5,3.0,15.0,NaN,In-store,2023-06-02
5916,TXN_2721997,Cake,3,3.0,9.0,NaN,Takeaway,2023-05-20
6816,TXN_2526267,Sandwich,UNKNOWN,4.0,20.0,Cash,In-store,2023-04-06
1953,TXN_7125945,Cake,3,3.0,9.0,Credit Card,In-store,2023-01-30
7333,TXN_9482559,Cookie,1,1.0,1.0,NaN,In-store,2023-08-04

In [7]:
sample.dropna(subset=['Item']) # menghapus baris yang null dalam kolom item

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2769,TXN_2849719,Coffee,5,2.0,10.0,Digital Wallet,Takeaway,2023-06-23
1762,TXN_9749333,Cookie,5,1.0,5.0,Cash,In-store,2023-02-27
7258,TXN_7362776,Cookie,NaN,1.0,5.0,NaN,In-store,2023-01-26
6427,TXN_4197851,Salad,ERROR,5.0,15.0,Digital Wallet,In-store,2023-02-05
8118,TXN_4822216,Cake,1,3.0,3.0,NaN,NaN,2023-09-03
6857,TXN_7046631,ERROR,4,2.0,8.0,Digital Wallet,In-store,2023-05-18
1722,TXN_3873718,ERROR,1,5.0,5.0,Cash,In-store,2023-03-07
7578,TXN_4532475,Coffee,ERROR,2.0,2.0,Digital Wallet,NaN,2023-04-23
8471,TXN_8783484,Smoothie,1,4.0,4.0,Cash,In-store,2023-11-20
5998,TXN_4335735,Coffee,2,2.0,4.0,NaN,NaN,2023-04-07
6115,TXN_9672367,Cookie,2,1.0,2.0,NaN,In-store,2023-12-21
3369,TXN_6431703,Sandwich,1,4.0,NaN,Credit Card,Takeaway,2023-08-25
5894,TXN_8499618,Cake,2,3.0,6.0,ERROR,NaN,2023-05-23
7367,TXN_7951885,Salad,3,5.0,15.0,Credit Card,NaN,2023-12-08
5770,TXN_8776634,Juice,5,3.0,15.0,NaN,In-store,2023-06-02
5916,TXN_2721997,Cake,3,3.0,9.0,NaN,Takeaway,2023-05-20
6816,TXN_2526267,Sandwich,UNKNOWN,4.0,20.0,Cash,In-store,2023-04-06
9800,TXN_2954833,Coffee,1,2.0,2.0,NaN,NaN,2023-01-29
1953,TXN_7125945,Cake,3,3.0,9.0,Credit Card,In-store,2023-01-30
7333,TXN_9482559,Cookie,1,1.0,1.0,NaN,In-store,2023-08-04