In [3]:
import pandas as pd

df = pd.read_csv('../Datasets/dirty_cafe_sales.csv')

In [4]:
sample = df.sample(20).replace(['UNKNOWN', 'ERROR'], pd.NA) # untuk mengambil data sample sebanyak 20, dan mengubah value unknown dan eror menjadi NaN

In [16]:
sample.fillna(0) #untuk mengisi semua kolom yang NaN

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
7621,TXN_2640771,Cookie,2,1.0,2.0,Digital Wallet,Takeaway,2023-01-27
8579,TXN_1037486,Salad,5,5.0,25.0,Digital Wallet,In-store,0
1180,TXN_4176373,Cookie,3,1.0,3.0,Cash,0,2023-03-28
5444,TXN_7732813,Tea,0,1.5,3.0,Credit Card,Takeaway,2023-07-16
1682,TXN_3648327,Cake,1,3.0,3.0,Digital Wallet,Takeaway,2023-08-17
919,TXN_2526667,0,3,3.0,9.0,Digital Wallet,In-store,2023-06-10
7102,TXN_2437751,Sandwich,1,4.0,4.0,0,In-store,2023-03-18
6030,TXN_6941542,Sandwich,3,4.0,12.0,0,In-store,2023-09-27
8525,TXN_7155957,Salad,5,5.0,25.0,Digital Wallet,In-store,2023-02-22
4046,TXN_9202190,Sandwich,0,4.0,20.0,0,In-store,2023-08-25
9723,TXN_6343367,Juice,2,3.0,6.0,0,In-store,2023-09-17
1471,TXN_1757340,Cake,2,3.0,6.0,Credit Card,In-store,2023-12-29
3668,TXN_6249023,Juice,1,3.0,3.0,Credit Card,0,2023-11-03
1009,TXN_3426892,Salad,4,5.0,20.0,Credit Card,0,2023-05-23
1776,TXN_4255767,Juice,1,3.0,3.0,0,0,2023-05-25
641,TXN_2962976,Juice,0,3.0,0,0,0,2023-03-17
1066,TXN_6148397,Tea,4,1.5,6.0,0,In-store,2023-03-20
5472,TXN_8211146,Sandwich,5,4.0,20.0,Digital Wallet,Takeaway,2023-04-30
522,TXN_2947822,Cake,4,3.0,12.0,Digital Wallet,In-store,2023-10-27
4819,TXN_7894558,Coffee,2,2.0,4.0,0,0,2023-01-04

In [8]:
sample['Payment Method'] = sample['Payment Method'].fillna(0) # Khusus kolomp payment method
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
7382,TXN_4064310,Tea,4,1.5,6.0,Cash,Takeaway,2023-07-24
1600,TXN_3850274,Juice,5,3.0,15.0,0,NaN,2023-09-08
6122,TXN_1026050,Cake,1,3.0,3.0,0,NaN,2023-04-23
2737,TXN_9470768,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-09-27
9976,TXN_3528020,Cookie,1,1.0,1.0,0,Takeaway,2023-08-26
141,TXN_2368126,Cake,5,3.0,15.0,0,In-store,2023-12-06
4819,TXN_7894558,Coffee,2,2.0,4.0,0,NaN,2023-01-04
9006,TXN_8795794,Sandwich,3,4.0,12.0,Cash,In-store,2023-02-13
7751,TXN_4719069,Juice,2,3.0,6.0,Digital Wallet,NaN,2023-01-04
1806,TXN_2192787,Sandwich,5,4.0,20.0,Cash,In-store,2023-01-01
8456,TXN_5548756,Cookie,4,1.0,4.0,Credit Card,NaN,2023-09-09
3339,TXN_2793054,Smoothie,4,4.0,16.0,0,Takeaway,2023-04-29
9187,TXN_5949199,Tea,5,1.5,7.5,0,In-store,2023-02-28
3735,TXN_2377708,Cookie,1,1.0,1.0,0,Takeaway,2023-01-03
4225,TXN_5380198,Cake,3,3.0,9.0,0,NaN,NaN
1736,TXN_6638051,Smoothie,2,4.0,8.0,Cash,NaN,2023-11-05
4724,TXN_3619141,Cookie,4,1.0,4.0,Digital Wallet,In-store,2023-09-30
2718,TXN_2661443,Juice,2,3.0,6.0,Credit Card,NaN,2023-06-30
9958,TXN_4125474,NaN,2,5.0,10.0,Credit Card,In-store,2023-08-02
3856,TXN_7899761,Juice,2,3.0,6.0,0,In-store,2023-10-08

In [15]:
# Mengisi data dengan Ffill dan Bfill
sample = df.head(20).replace(['UNKNOWN', 'ERROR'], pd.NA) # untuk mengambil data sample sebanyak 20, dan mengubah value unknown dan eror menjadi NaN

In [17]:
sample['Payment Method'] = sample['Payment Method'].ffill # Mengisi data menggunakan ffill atau melihat data ke atas, dan bfill melihat data kebawah
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,NaN
12,TXN_7619095,Sandwich,2,4.0,8.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-06-01
14,TXN_8915701,NaN,2,1.5,3.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-01-15

In [19]:
sample['Payment Method'] = sample['Payment Method'].bfill()
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,NaN
12,TXN_7619095,Sandwich,2,4.0,8.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-06-01
14,TXN_8915701,NaN,2,1.5,3.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-01-15