In [2]:
import pandas as pd

df = pd.read_csv('../Datasets/dirty_cafe_sales.csv')

In [3]:
sample = df.sample(20).replace(['UNKNOWN', 'ERROR'], pd.NA) # untuk mengambil data sample sebanyak 20, dan mengubah value unknown dan eror menjadi NaN

In [4]:
sample.fillna(0) #untuk mengisi semua kolom yang NaN dengan nilai 0

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
5863,TXN_4430474,Cake,2,3.0,6.0,Digital Wallet,0,2023-06-08
9,TXN_2064365,Sandwich,5,4.0,20.0,0,In-store,2023-12-31
8751,TXN_8359693,Sandwich,2,4.0,8.0,Digital Wallet,In-store,2023-10-23
1159,TXN_5041555,0,4,1.5,6.0,Digital Wallet,0,2023-08-26
5379,TXN_6272473,Coffee,4,2.0,8.0,Cash,Takeaway,2023-03-06
801,TXN_2393500,Juice,1,0,3.0,Credit Card,In-store,2023-12-15
4125,TXN_8936086,Sandwich,4,4.0,16.0,0,In-store,2023-11-27
7735,TXN_1444932,Smoothie,1,4.0,4.0,Cash,In-store,2023-05-24
7741,TXN_2111973,Tea,4,1.5,6.0,Digital Wallet,In-store,0
9537,TXN_1874601,Coffee,4,2.0,8.0,0,0,2023-12-10
5986,TXN_1598214,Juice,1,0,3.0,Credit Card,Takeaway,2023-01-07
4762,TXN_3150614,Sandwich,1,4.0,4.0,Cash,Takeaway,2023-08-06
4978,TXN_3301517,Salad,0,5.0,25.0,Credit Card,In-store,2023-04-13
2167,TXN_2004781,Sandwich,5,0,20.0,0,Takeaway,2023-04-20
8540,TXN_4840522,Smoothie,3,4.0,12.0,0,In-store,2023-06-16
3020,TXN_4527464,Tea,4,1.5,6.0,0,In-store,2023-08-09
1709,TXN_4486700,Cake,2,3.0,6.0,Digital Wallet,Takeaway,2023-02-08
3990,TXN_8632653,Juice,2,3.0,6.0,0,In-store,2023-12-24
9346,TXN_2977905,Smoothie,3,4.0,12.0,0,0,2023-06-23
329,TXN_8894157,Sandwich,4,4.0,16.0,Credit Card,0,0

In [14]:
sample['Payment Method'] = sample['Payment Method'].fillna(0) # Khusus kolomp payment method
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,NaN
12,TXN_7619095,Sandwich,2,4.0,8.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-06-01
14,TXN_8915701,NaN,2,1.5,3.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,<bound method NDFrame.ffill of 0 Credit...,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,<bound method NDFrame.ffill of 0 Credit...,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,<bound method NDFrame.ffill of 0 Credit...,Takeaway,2023-01-15

In [15]:
# Mengisi data dengan Ffill dan Bfill
sample = df.head(20).replace(['UNKNOWN', 'ERROR'], pd.NA) # untuk mengambil data sample sebanyak 20, dan mengubah value unknown dan eror menjadi NaN

In [16]:
sample['Payment Method'] = sample['Payment Method'].ffill() # Mengisi data menggunakan ffill atau melihat data ke atas, dan bfill melihat data kebawah
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,Credit Card,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,Credit Card,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,Cash,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,Cash,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,NaN
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,Cash,Takeaway,2023-06-01
14,TXN_8915701,NaN,2,1.5,3.0,Cash,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,Credit Card,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15

In [17]:
sample['Payment Method'] = sample['Payment Method'].bfill()
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,Credit Card,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,Credit Card,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,Cash,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,Cash,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,NaN
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,Cash,Takeaway,2023-06-01
14,TXN_8915701,NaN,2,1.5,3.0,Cash,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,Credit Card,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15

In [9]:
# Mengisi missing value dengaen mean, median, dan modus (ini yang rata rata dipakai)

# Mean digunakan ketika : data bersifat numerik, tidak banyak outlier, dan rata rata harus merepresentasikan pusat data baik
# Contoh penggunaan mean : data nilai ujian siswa, dimana dilai hilang dan data penjualan produk dengan sedikti nilai hilang

# Median digunakna ketika : data bersifat numerik tetapi tidak terdistrubusi secara normal, dan terdapat banyak outlier yang memengaruhi rata rata
# contoh penggunaan median : data durasi kunjungan pelanggan ke situs web

# Modus digunakan ketika : data bersifat kategorikal atau nominal, kategori dengan frekuensi tertinggi dianggap paling mewakili data
# Contoh penggunaan Modus : data preferensi peloanggan (misal warna favorit, produk favorit), data demografis seperti gender, atau wilayah geografis

In [20]:
# Mengisi data dengan Ffill dan Bfill
sample = df.sample(20).replace(['UNKNOWN', 'ERROR'], pd.NA) # untuk mengambil data sample sebanyak 20, dan mengubah value unknown dan eror menjadi NaN
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
7974,TXN_1492585,Sandwich,NaN,4.0,12.0,Cash,Takeaway,2023-01-17
5309,TXN_4360906,Sandwich,2,4.0,8.0,NaN,In-store,2023-06-11
6183,TXN_8053946,Tea,1,1.5,1.5,NaN,Takeaway,2023-09-18
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17
6646,TXN_6383779,Coffee,1,2.0,2.0,NaN,NaN,2023-11-29
5386,TXN_7894534,Tea,3,1.5,4.5,Credit Card,In-store,2023-03-16
5754,TXN_3868402,Coffee,3,2.0,6.0,Cash,In-store,2023-01-21
2949,TXN_5544904,Salad,5,5.0,25.0,NaN,NaN,2023-04-19
8067,TXN_5812552,Cake,1,NaN,3.0,NaN,NaN,2023-09-17
6406,TXN_6959328,Sandwich,3,4.0,12.0,Credit Card,Takeaway,2023-04-23
3572,TXN_2371464,Smoothie,4,4.0,16.0,Cash,In-store,2023-09-20
6723,TXN_7835785,Salad,1,5.0,5.0,Cash,In-store,2023-10-12
1868,TXN_5108804,Juice,1,NaN,3.0,Digital Wallet,In-store,2023-09-26
4114,TXN_7887682,NaN,2,2.0,4.0,Credit Card,Takeaway,2023-06-17
6804,TXN_9786525,Cake,5,3.0,15.0,NaN,Takeaway,2023-02-19
6624,TXN_1840584,Cake,5,3.0,15.0,Digital Wallet,NaN,2023-05-28
6822,TXN_7213830,NaN,5,3.0,15.0,Credit Card,NaN,2023-08-04
8648,TXN_5452978,Salad,2,5.0,10.0,Cash,In-store,2023-04-10
2042,TXN_1203954,Sandwich,1,4.0,4.0,Digital Wallet,NaN,2023-08-12
1191,TXN_6202015,Cookie,2,1.0,2.0,Credit Card,Takeaway,2023-08-22

In [23]:
sample['Total Spent'] = sample['Total Spent'].fillna(sample['Total Spent'].median()) # harus bertipe angka

In [ ]:
sample['Total Spent'] = sample['Total Spent'].fillna(sample['Total Spent'].mean()) # harus bertipe angka

In [26]:
sample['Item'] = sample['Item'].fillna(sample['Item'].mode()) # harus bertipe huruf

In [27]:
sample

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
7974,TXN_1492585,Sandwich,NaN,4.0,12.0,Cash,Takeaway,2023-01-17
5309,TXN_4360906,Sandwich,2,4.0,8.0,NaN,In-store,2023-06-11
6183,TXN_8053946,Tea,1,1.5,1.5,NaN,Takeaway,2023-09-18
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17
6646,TXN_6383779,Coffee,1,2.0,2.0,NaN,NaN,2023-11-29
5386,TXN_7894534,Tea,3,1.5,4.5,Credit Card,In-store,2023-03-16
5754,TXN_3868402,Coffee,3,2.0,6.0,Cash,In-store,2023-01-21
2949,TXN_5544904,Salad,5,5.0,25.0,NaN,NaN,2023-04-19
8067,TXN_5812552,Cake,1,NaN,3.0,NaN,NaN,2023-09-17
6406,TXN_6959328,Sandwich,3,4.0,12.0,Credit Card,Takeaway,2023-04-23
3572,TXN_2371464,Smoothie,4,4.0,16.0,Cash,In-store,2023-09-20
6723,TXN_7835785,Salad,1,5.0,5.0,Cash,In-store,2023-10-12
1868,TXN_5108804,Juice,1,NaN,3.0,Digital Wallet,In-store,2023-09-26
4114,TXN_7887682,NaN,2,2.0,4.0,Credit Card,Takeaway,2023-06-17
6804,TXN_9786525,Cake,5,3.0,15.0,NaN,Takeaway,2023-02-19
6624,TXN_1840584,Cake,5,3.0,15.0,Digital Wallet,NaN,2023-05-28
6822,TXN_7213830,NaN,5,3.0,15.0,Credit Card,NaN,2023-08-04
8648,TXN_5452978,Salad,2,5.0,10.0,Cash,In-store,2023-04-10
2042,TXN_1203954,Sandwich,1,4.0,4.0,Digital Wallet,NaN,2023-08-12
1191,TXN_6202015,Cookie,2,1.0,2.0,Credit Card,Takeaway,2023-08-22

In [1]:
# Mengisi missing value dengan interpolasi (interpolate)
# Interpolasi digunakan untuk mengisi nilai kosong berdasarkan pola atau trend dalam data itu sendiri, cocok untuk data numerik atau data yang berurutan

# kapan digunakan : data numerik berurutan, data time series, memperkirakan nilai yanghilang berdasarkan tren
# seperti : dataset cuaca (suhu , kelembapan dll), data keuangan , data sensor

In [5]:
data = {
    'Tanggal' : [
        '2026-01-01','2026-01-02','2026-01-03','2026-01-04',
        '2026-01-05','2026-01-06','2026-01-07','2026-01-08',
        '2026-01-09','2026-01-010'
    ],
    'Harga_Saham' : [
        100.0, 102.0, None, 108.0,
        None, None, 115.0, 117.0,
        None, 120.0
    ]
}

df = pd.DataFrame(data)
df

       Tanggal  Harga_Saham
0   2026-01-01        100.0
1   2026-01-02        102.0
2   2026-01-03          NaN
3   2026-01-04        108.0
4   2026-01-05          NaN
5   2026-01-06          NaN
6   2026-01-07        115.0
7   2026-01-08        117.0
8   2026-01-09          NaN
9  2026-01-010        120.0

In [8]:
df['Harga_Saham'] = pd.to_numeric(df['Harga_Saham'], errors='coerce')
df['Harga_Saham'] = df['Harga_Saham'].interpolate(method='linear')
df

       Tanggal  Harga_Saham
0   2026-01-01   100.000000
1   2026-01-02   102.000000
2   2026-01-03   105.000000
3   2026-01-04   108.000000
4   2026-01-05   110.333333
5   2026-01-06   112.666667
6   2026-01-07   115.000000
7   2026-01-08   117.000000
8   2026-01-09   118.500000
9  2026-01-010   120.000000

In [9]:
# Mengisi missing value dengan replace 

# Mengganti nilai kosong dengan nilai deskriptif "tidak tersedia", "Tidak tersedia"
# Contoh penggunaan : dalam hilang data sperti nomor telpon, email yang kosong, kuisioner yang kosong

data = {
    'Nama' : ['asep', None, 'supri'],
    'Umur' : [25, 24, None],
    'Kota' : ['Jakarta', None , 'Bandung'],
}

df = pd.DataFrame(data)
df

    Nama  Umur     Kota
0   asep  25.0  Jakarta
1    NaN  24.0      NaN
2  supri   NaN  Bandung

In [12]:
df.replace({None: 'Data hilang'})

          Nama  Umur         Kota
0         asep  25.0      Jakarta
1  Data hilang  24.0  Data hilang
2        supri   NaN      Bandung