Data yang tidak konsisten dapat menyebabkan analisis menjadi tidak akurat dan menylitkan pengolahan data lebih lanjut. contohnya seperti perbedaan format pada seperti penggunaan besar/kecil ataua danya spasi tambahan

### kasus umum :
1. perbedaan huruf besar dan kecil
2. spasi tambahan
3. format tanggal yagn berbeda
4. karakter khusus
5. data yang tidak terstruktur

### Cara mengatasi inkonsistensi format dana
1. Menggunakan Fungsi standarisasi pada sofware atau toolz
   * bisa menggunakan excel (trim, upper,lower)
   * menggunakan library pandas contoh :
       * * Mengubah huruf menjadi kecil atau besar -> data['column'].str.lower()
       * * Menghapus spasi tambahan -> data['column'].str.strip()
       * * Menstandarkan format tanggal -> pd.to_datetime(data['date_column'])
2. Menggunakan regex
   * gunakan regex untuk membersihkan karakter tertentu atau menyesuaikan pola contoh menghapus karakter selain angka :
     * * data['column'].str.replace(r'[^0-9]', '')
3. membuat mapping table
   * buat referensi untuk standarisasi nilaitertentu seperti 'jalan' menjadi 'Jl'
4. Automasi dengan script ( terutama kalau dataset nya besar)
5. validasi dan verifikasi

In [5]:
import pandas as pd

df = pd.read_csv('../Datasets/dirty_cafe_sales.csv')
sample = df.sample(30)
display(sample)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6202,TXN_7832527,Cake,3,3.0,9.0,Cash,In-store,2023-01-26
4340,TXN_9395087,Tea,1,1.5,1.5,Cash,In-store,2023-06-12
7702,TXN_9292025,NaN,2,5.0,10.0,Digital Wallet,In-store,2023-03-25
3174,TXN_1778597,Cookie,3,1.0,UNKNOWN,Cash,NaN,2023-09-28
2261,TXN_6811368,Coffee,4,2.0,8.0,NaN,Takeaway,2023-02-18
388,TXN_3515730,NaN,1,1.0,1.0,Credit Card,NaN,2023-08-14
2873,TXN_5052998,Juice,3,3.0,9.0,Credit Card,NaN,2023-10-07
253,TXN_3544789,Tea,4,1.5,ERROR,UNKNOWN,In-store,2023-07-14
4351,TXN_9407000,Sandwich,4,4.0,16.0,NaN,Takeaway,2023-10-03
9416,TXN_9344399,Cookie,2,1.0,2.0,UNKNOWN,NaN,2023-12-04
4847,TXN_7332957,Sandwich,5,4.0,20.0,Digital Wallet,NaN,2023-07-26
5478,TXN_5104848,Tea,2,1.5,3.0,NaN,Takeaway,2023-01-22
759,TXN_7399897,NaN,4,3.0,12.0,NaN,Takeaway,2023-11-14
9225,TXN_3879052,Coffee,3,2.0,6.0,Credit Card,NaN,2023-12-14
1041,TXN_3854285,Salad,3,5.0,15.0,Cash,Takeaway,2023-07-18
8452,TXN_6266187,Tea,5,1.5,7.5,Credit Card,In-store,NaN
6949,TXN_3130302,Smoothie,3,4.0,12.0,Credit Card,In-store,UNKNOWN
4318,TXN_3412484,Cake,4,3.0,12.0,NaN,Takeaway,2023-09-06
4980,TXN_3764807,Smoothie,2,NaN,8.0,NaN,NaN,2023-08-28
3007,TXN_5282529,Tea,5,1.5,7.5,Credit Card,Takeaway,2023-04-13
9727,TXN_3562418,UNKNOWN,2,4.0,8.0,Digital Wallet,UNKNOWN,2023-08-13
8218,TXN_1708928,Smoothie,1,4.0,4.0,ERROR,NaN,UNKNOWN
1786,TXN_1923349,ERROR,4,ERROR,6.0,NaN,NaN,2023-07-06
7502,TXN_2199647,Salad,1,5.0,5.0,Cash,NaN,2023-05-05
3217,TXN_9841222,Sandwich,5,4.0,20.0,Credit Card,ERROR,2023-04-23
9756,TXN_8131570,Salad,4,5.0,20.0,NaN,In-store,2023-12-02
8266,TXN_3886177,Cake,3,3.0,9.0,NaN,Takeaway,2023-07-17
1527,TXN_8356338,Salad,5,5.0,25.0,Credit Card,In-store,2023-08-06
2880,TXN_5017038,Sandwich,3,4.0,12.0,NaN,NaN,2023-05-25
3695,TXN_7737862,Cookie,2,1.0,2.0,Credit Card,NaN,2023-08-29

In [8]:
sample['Transaction ID'] = df['Transaction ID'].str.replace('[_ ]','-', regex=True).str.lower() # str lower mereplace huruf menjadi kecil
display(sample) # contoh me replace _ menjadi -

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6202,txn-7832527,Cake,3,3.0,9.0,Cash,In-store,2023-01-26
4340,txn-9395087,Tea,1,1.5,1.5,Cash,In-store,2023-06-12
7702,txn-9292025,NaN,2,5.0,10.0,Digital Wallet,In-store,2023-03-25
3174,txn-1778597,Cookie,3,1.0,UNKNOWN,Cash,NaN,2023-09-28
2261,txn-6811368,Coffee,4,2.0,8.0,NaN,Takeaway,2023-02-18
388,txn-3515730,NaN,1,1.0,1.0,Credit Card,NaN,2023-08-14
2873,txn-5052998,Juice,3,3.0,9.0,Credit Card,NaN,2023-10-07
253,txn-3544789,Tea,4,1.5,ERROR,UNKNOWN,In-store,2023-07-14
4351,txn-9407000,Sandwich,4,4.0,16.0,NaN,Takeaway,2023-10-03
9416,txn-9344399,Cookie,2,1.0,2.0,UNKNOWN,NaN,2023-12-04
4847,txn-7332957,Sandwich,5,4.0,20.0,Digital Wallet,NaN,2023-07-26
5478,txn-5104848,Tea,2,1.5,3.0,NaN,Takeaway,2023-01-22
759,txn-7399897,NaN,4,3.0,12.0,NaN,Takeaway,2023-11-14
9225,txn-3879052,Coffee,3,2.0,6.0,Credit Card,NaN,2023-12-14
1041,txn-3854285,Salad,3,5.0,15.0,Cash,Takeaway,2023-07-18
8452,txn-6266187,Tea,5,1.5,7.5,Credit Card,In-store,NaN
6949,txn-3130302,Smoothie,3,4.0,12.0,Credit Card,In-store,UNKNOWN
4318,txn-3412484,Cake,4,3.0,12.0,NaN,Takeaway,2023-09-06
4980,txn-3764807,Smoothie,2,NaN,8.0,NaN,NaN,2023-08-28
3007,txn-5282529,Tea,5,1.5,7.5,Credit Card,Takeaway,2023-04-13
9727,txn-3562418,UNKNOWN,2,4.0,8.0,Digital Wallet,UNKNOWN,2023-08-13
8218,txn-1708928,Smoothie,1,4.0,4.0,ERROR,NaN,UNKNOWN
1786,txn-1923349,ERROR,4,ERROR,6.0,NaN,NaN,2023-07-06
7502,txn-2199647,Salad,1,5.0,5.0,Cash,NaN,2023-05-05
3217,txn-9841222,Sandwich,5,4.0,20.0,Credit Card,ERROR,2023-04-23
9756,txn-8131570,Salad,4,5.0,20.0,NaN,In-store,2023-12-02
8266,txn-3886177,Cake,3,3.0,9.0,NaN,Takeaway,2023-07-17
1527,txn-8356338,Salad,5,5.0,25.0,Credit Card,In-store,2023-08-06
2880,txn-5017038,Sandwich,3,4.0,12.0,NaN,NaN,2023-05-25
3695,txn-7737862,Cookie,2,1.0,2.0,Credit Card,NaN,2023-08-29

## Contoh lainnya :
* str.strip() -> untuk menghapus spasi
* str.title() - > Mengubah huruf pertama menjadi kapital 'tangerang' -> 'Tangerang'